// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuditLogEvent struct {
	ID                string         `json:"id"`
	Timestamp         time.Time      `json:"timestamp"`
	ServiceName       string         `json:"service_name"`
	Operation         string         `json:"operation"`
	ActorID           string         `json:"actor_id"`
	ActorType         string         `json:"actor_type"`
	AffectedResources []string       `json:"affected_resources"`
	Metadata          map[string]any `json:"metadata"`
	IntegrityHash     string         `json:"integrity_hash"`
}

type Cursor struct {
	Timestamp time.Time `json:"Timestamp"`
	ID        string    `json:"Id"`
}

type Query struct {
}

type SearchQuery struct {
	ServiceName       *string        `json:"serviceName,omitempty"`
	Operation         *string        `json:"operation,omitempty"`
	ActorID           *string        `json:"actorID,omitempty"`
	ActorType         *string        `json:"actorType,omitempty"`
	AffectedResources []*string      `json:"affectedResources,omitempty"`
	Metadata          map[string]any `json:"metadata,omitempty"`
	Cursor            *Cursor        `json:"cursor,omitempty"`
}
